services:
  my-keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "8080", --import-realm]
    ports:
      - "8080:8080"          
    networks:
      - local_network
    volumes:
      - ./:/opt/keycloak/data/import
networks:
  local_network:
    driver: bridge